language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy

install:
    # argparse is not in the 2.6 standard library
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse; fi

script:
    - python -m pytest
    - python -m pytest --doctest-modules natsort
    - python -m pytest README.rst
