dist: xenial
sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

# By default do not build "extras". Builds with "extras" will be included manually below.
env: WITH_EXTRAS=""

jobs:
  include:
    - python: "2.7"
      env: WITH_EXTRAS="fast,icu"
      addons:
        apt:
          packages:
          - libicu-dev
          - language-pack-de
          - language-pack-en
    - python: "3.6"
      env: WITH_EXTRAS="fast,icu"
      addons:
        apt:
          packages:
          - libicu-dev
          - language-pack-de
          - language-pack-en
    - stage: code-quality
      python: "3.6"
      install: pip install flake8 flake8-import-order flake8-bugbear pep8-naming twine check-manifest
      script:
      - flake8
      - check-manifest --ignore ".github*,*.md,.coveragerc"
      - python setup.py sdist
      - twine check dist/*

install:
- pip install -U pip
- pip install tox-travis codacy-coverage codecov

script:
- tox

stages:
- code-quality
- test

after_success:
- coverage xml
- python-codacy-coverage -r coverage.xml
- codecov
