language: python
python:
- "2.6"
- "2.7"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "pypy"

sudo: false

env:
- WITH_OPTIONS=true
- WITH_OPTIONS=false

matrix:
  exclude:
    - python: "pypy"
      env: WITH_OPTIONS=true
    - python: "2.6"
      env: WITH_OPTIONS=true

addons:
  apt:
    packages:
    - libicu-dev
    - language-pack-de
    - language-pack-en

install:
- pip install -U pip
- pip install -rrequirements.txt -rtesting-requirements.txt
- if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install -rcpython-testing-requirements.txt; fi
- if [[ $WITH_OPTIONS == true ]]; then pip install -roptional-requirements.txt; fi
- pip install tox-travis coveralls

script:
- tox

after_success:
  coveralls
